# from turtle import Turtle, Screen
#
# timmy=Turtle()
# timmy.color("DarkSeaGreen")
# timmy.shape("turtle")
# timmy.forward(100)
# my_screen=Screen()
# print(my_screen.canvheight)
# my_screen.exitonclick()
from prettytable import PrettyTable
table=PrettyTable()
table.align="l"
table.hrules=True
table.field_names=["Number","Pokemon Name","Type"]
table.add_rows(
    [
        ['#001','Chespin','Grass'],
        ['#002','Quilladin','Grass'],
        ['#003','Chesnaught','Grass · Fighting'],
        ['#004','Fennekin','Fire'],
        ['#005','Braixen','Fire'],
        ['#006','Delphox','Fire · Psychic'],
        ['#007','Froakie','Water'],
        ['#008','Frogadier','Water'],
        ['#009','Greninja','Water · Dark'],
        ['#010','Bunnelby','Normal'],
        ['#011','Diggersby','Normal · Ground'],
        ['#012','Zigzagoon','Normal'],
        ['#013','Linoone','Normal'],
        ['#014','Fletchling','Normal · Flying'],
        ['#015','Fletchinder','Fire · Flying'],
        ['#016','Talonflame','Fire · Flying'],
        ['#017','Pidgey','Normal · Flying'],
        ['#018','Pidgeotto','Normal · Flying'],
        ['#019','Pidgeot','Normal · Flying'],
        ['#020','Scatterbug','Bug'],
        ['#021','Spewpa','Bug'],
        ['#022','Vivillon','Bug · Flying'],
        ['#023','Caterpie','Bug'],
        ['#024','Metapod','Bug'],
        ['#025','Butterfree','Bug · Flying'],
        ['#026','Weedle','Bug · Poison'],
        ['#027','Kakuna','Bug · Poison'],
        ['#028','Beedrill','Bug · Poison'],
        ['#029','Pansage','Grass'],
        ['#030','Simisage','Grass'],
        ['#031','Pansear','Fire'],
        ['#032','Simisear','Fire'],
        ['#033','Panpour','Water'],
        ['#034','Simipour','Water'],
        ['#035','Pichu','Electric'],
        ['#036','Pikachu','Electric'],
        ['#037','Raichu','Electric'],
        ['#038','Bidoof','Normal'],
        ['#039','Bibarel','Normal · Water'],
        ['#040','Dunsparce','Normal'],
        ['#041','Azurill','Normal · Fairy'],
        ['#042','Marill','Water · Fairy'],
        ['#043','Azumarill','Water · Fairy'],
        ['#044','Burmy','Bug'],
        ['#045','Wormadam','Bug · Grass'],
        ['#046','Mothim','Bug · Flying'],
        ['#047','Surskit','Bug · Water'],
        ['#048','Masquerain','Bug · Flying'],
        ['#049','Magikarp','Water'],
        ['#050','Gyarados','Water · Flying'],
        ['#051','Corphish','Water'],
        ['#052','Crawdaunt','Water · Dark'],
        ['#053','Goldeen','Water'],
        ['#054','Seaking','Water'],
        ['#055','Carvanha','Water · Dark'],
        ['#056','Sharpedo','Water · Dark'],
        ['#057','Litleo','Fire · Normal'],
        ['#058','Pyroar','Fire · Normal'],
        ['#059','Psyduck','Water'],
        ['#060','Golduck','Water'],
        ['#061','Farfetchd','Normal · Flying'],
        ['#062','Riolu','Fi1ghting'],
        ['#063','Lucario','Fighting · Steel'],
        ['#064','Ralts','Psychic · Fairy'],
        ['#065','Kirlia','Psychic · Fairy'],
        ['#066','Gardevoir','Psychic · Fairy'],
        ['#067','Gallade','Psychic · Fighting'],
        ['#068','Flabébé','Fairy'],
        ['#069','Floette','Fairy'],
        ['#070','Florges','Fairy'],
        ['#071','Budew','Grass · Poison'],
        ['#072','Roselia','Grass · Poison'],
        ['#073','Roserade','Grass · Poison'],
        ['#074','Ledyba','Bug · Flying'],
        ['#075','Ledian','Bug · Flying'],
        ['#076','Combee','Bug · Flying'],
        ['#077','Vespiquen','Bug · Flying'],
        ['#078','Skitty','Normal'],
        ['#079','Delcatty','Normal'],
        ['#080','Bulbasaur','Grass · Poison'],
        ['#081','Ivysaur','Grass · Poison'],
        ['#082','Venusaur','Grass · Poison'],
        ['#083','Charmander','Fire'],
        ['#084','Charmeleon','Fire'],
        ['#085','Charizard','Fire · Flying'],
        ['#086','Squirtle','Water'],
        ['#087','Wartortle','Water'],
        ['#088','Blastoise','Water'],
        ['#089','Skiddo','Grass'],
        ['#090','Gogoat','Grass'],
        ['#091','Pancham','Fighting'],
        ['#092','Pangoro','Fighting · Dark'],
        ['#093','Furfrou','Normal'],
        ['#094','Doduo','Normal · Flying'],
        ['#095','Dodrio','Normal · Flying'],
        ['#096','Plusle','Electric'],
        ['#097','Minun','Electric'],
        ['#098','Gulpin','Poison'],
        ['#099','Swalot','Poison'],
        ['#100','Scraggy','Dark · Fighting'],
        ['#101','Scrafty','Dark · Fighting'],
        ['#102','Abra','Psychic'],
        ['#103','Kadabra','Psychic'],
        ['#104','Alakazam','Psychic'],
        ['#105','Oddish','Grass · Poison'],
        ['#106','Gloom','Grass · Poison'],
        ['#107','Vileplume','Grass · Poison'],
        ['#108','Bellossom','Grass'],
        ['#109','Sentret','Normal'],
        ['#110','Furret','Normal'],
        ['#111','Nincada','Bug · Ground'],
        ['#112','Ninjask','Bug · Flying'],
        ['#113','Shedinja','Bug · Ghost'],
        ['#114','Espurr','Psychic'],
        ['#115','Meowstic','Psychic'],
        ['#116','Kecleon','Normal'],
        ['#117','Honedge','Steel · Ghost'],
        ['#118','Doublade','Steel · Ghost'],
        ['#119','Aegislash','Steel · Ghost'],
        ['#120','Venipede','Bug · Poison'],
        ['#121','Whirlipede','Bug · Poison'],
        ['#122','Scolipede','Bug · Poison'],
        ['#123','Audino','Normal'],
        ['#124','Smeargle','Normal'],
        ['#125','Croagunk','Poison · Fighting'],
        ['#126','Toxicroak','Poison · Fighting'],
        ['#127','Ducklett','Water · Flying'],
        ['#128','Swanna','Water · Flying'],
        ['#129','Spritzee','Fairy'],
        ['#130','Aromatisse','Fairy'],
        ['#131','Swirlix','Fairy'],
        ['#132','Slurpuff','Fairy'],
        ['#133','Volbeat','Bug'],
        ['#134','Illumise','Bug'],
        ['#135','Hoppip','Grass · Flying'],
        ['#136','Skiploom','Grass · Flying'],
        ['#137','Jumpluff','Grass · Flying'],
        ['#138','Munchlax','Normal'],
        ['#139','Snorlax','Normal'],
        ['#140','Whismur','Normal'],
        ['#141','Loudred','Normal'],
        ['#142','Exploud','Normal'],
        ['#143','Meditite','Fighting · Psychic'],
        ['#144','Medicham','Fighting · Psychic'],
        ['#145','Zubat','Poison · Flying'],
        ['#146','Golbat','Poison · Flying'],
        ['#147','Crobat','Poison · Flying'],
        ['#148','Axew','Dragon'],
        ['#149','Fraxure','Dragon'],
        ['#150','Haxorus','Dragon'],
        ['#151','Diancie','Rock · Fairy'],
        ['#152','Hoopa','Psychic · Ghost'],
        ['#153','Volcanion','Fire · Water'],
    ]


)
print(table)